Main/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings    #youssef
from django.conf.urls.static import static  #youssef
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("course.urls")),#include("course.urls",namespace='course')
    path('account/', include("account.urls",namespace='account')),
]
if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('view-profile/', views.view_profile, name='view-profile'),
    path('sign-in/', views.sign_in, name='sign_in'),
    path('sign-out/', views.sign_out, name='sign_out'),
]

course/urls.py
from django.urls import path
from .  import views
app_name='course'
urlpatterns = [
        path('', views.subject_courses_list,name="subject_courses_list"),
        path('course/<slug:slug>/', views.course_detail, name='course_detail'),
        path('course/add-course', views.add_course, name='add_course'),
        path('course/edit-coures/<slug:slug>/', views.edit_course, name='edit_course'),
        path('course/<slug:slug>/add-module/', views.add_module, name='add_module'),
        path('course/enroll-course/<slug:slug>/', views.enroll_course, name='enroll_course'),
]
# course:enroll_course

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} E-Learning Platform {% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />   
  </head>

  <body class="bg-gray-100">
    <!-- Navbar -->
    <nav class="bg-white p-4 shadow-md">
      <div class="container mx-auto flex justify-between items-center">
        <a
          href="{% url 'course:subject_courses_list' %}"
          class="text-2xl font-bold text-gray-800"
          >E-Learn</a
        >
        <ul class="flex space-x-4">
          {% if user.is_authenticated %}
          <li>
            <a href="#" class="text-gray-600 hover:text-blue-500"
              >Welcome, {{request.user}}</a
            >
          </li>
          <li>
            <a
              href="{% url 'account:view-profile' %}"
              class="text-gray-600 hover:text-blue-500"
              >Profile</a
            >
          </li>
          {% endif %}

          <li>
            <a href="#" class="text-gray-600 hover:text-blue-500">Courses</a>
          </li>
          <li>
            <a href="#" class="text-gray-600 hover:text-blue-500">Categories</a>
          </li>

          {% if user.is_authenticated %}

          <li>
            <a
              href="{% url 'account:sign_out' %}"
              class="text-gray-600 hover:text-blue-500"
              >Sign-out</a
            >
          </li>
          {% else %}

          <!-- -------------- -->
          <!-- ------------------- -->
          <li>
            <a
              href="{% url 'account:sign_in' %}"
              class="text-gray-600 hover:text-blue-500"
              >Sign-In</a
            >
          </li>
          <li>
            <a
              href="{% url 'account:sign_up' %}"
              class="text-gray-600 hover:text-blue-500"
              >Sign-Up</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %} {% endblock content %}
  </body>
</html>

templates/message.html
{% if messages %}
<div class="max-w-4xl mx-auto mt-5 bg-white p-8 rounded shadow">
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">{{ message }}</div>

  {% endfor %}
</div>

{% endif %}

<!-- flowbite.com/docs/components/alerts/ -->

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    test
</html>